targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: false
      freezed:
        options:
          format: true
          to_json: false
          copy_with: false
          when: false
          map: false
