targets:
  $default:
    builders:
      json_serializable:
        options:
          # create_to_json: false
          explicit_to_json: true
      freezed:
        options:
          # to_json: true
          when: false
          map: false
