name: mtb
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/deminearchiver/material-color-utilities-dart
resolution: workspace
publish_to: none

executables:
  mtb:

environment:
  sdk: ^3.8.0

dependencies:
  material_color_utilities:
    path: ../..

  args: ^2.7.0
  dcli: ^8.2.0
  csslib: ^1.0.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  dart_console: ^4.1.2
  promptly: ^1.0.0-alpha.9
  intl: ^0.20.2
  change_case: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  test: ^1.26.3
