name: mtb
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/deminearchiver/material-color-utilities-dart
resolution: workspace
publish_to: none

executables:
  mtb:

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  material_color_utilities:
    path: ../../packages/material_color_utilities
  args: ^2.5.0
  dcli: ^7.0.3
  csslib: ^1.0.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  dart_console: ^4.1.1
  promptly: ^1.0.0-alpha.8
  intl: ^0.19.0
  change_case: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  test: ^1.24.0
